---

- hosts: local
  connection: local
  become: false
  gather_facts: false
  tasks:

  - name: Wait for Girder Server
    local_action:
      module: wait_for host="{{ ghost }}" port="{{ gport }}" delay=10

  - name: Ensure Privileged User
    girder:
      host: "{{ ghost }}"
      port: "{{ gport }}"
      scheme: "{{ gscheme }}"
      user:
        login: "{{ admin_name }}"
        password: "{{ admin_pass }}"
        firstName: Girder
        lastName: Admin
        email: "admin@girder.girder"
        admin: true
      state: present

  - name: Record Privileged User Token
    girder:
      host: "{{ ghost }}"
      port: "{{ gport }}"
      scheme: "{{ gscheme }}"
      username: "{{ admin_name }}"
      password: "{{ admin_pass }}"
      get:
        path: "user/me"
    register: admin

  - name: Ensure Default Assetstore
    girder:
      host: "{{ ghost }}"
      port: "{{ gport }}"
      scheme: "{{ gscheme }}"
      token: "{{ admin['token'] }}"
      assetstore:
        name: "Local"
        type: "filesystem"
        current: true
        root: "{{ assetstore }}"
      state: present

  - name: Activate Girder Plugins
    girder:
      host: "{{ ghost }}"
      port: "{{ gport }}"
      scheme: "{{ gscheme }}"
      token: "{{ admin['token'] }}"
      plugins:
        - jobs
        - worker
        - geometa
        - resonantgeoview_server
        - large_image
      state: present

  - name: Restart Girder Server
    girder:
      host: "{{ ghost }}"
      port: "{{ gport }}"
      scheme: "{{ gscheme }}"
      token: "{{ admin['token'] }}"
      put:
        path: "system/restart"

  - name: Wait for Girder Server
    local_action:
      module: wait_for host="{{ ghost }}" port="{{ gport }}" delay=5

  - name: Update Girder System Settings
    girder:
      host: "{{ ghost }}"
      port: "{{ gport }}"
      scheme: "{{ gscheme }}"
      token: "{{ admin['token'] }}"
      setting:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      state: present

    with_items:
      # girder worker won't pickup these three for some reason
      # - key: "worker.broker"
      #   value: "{{ broker }}"

      # - key: "worker.backend"
      #   value: "{{ broker }}"

      # - key: "worker.api_url"
      #   value: "http://{{ ghost }}:{{ gport }}/api/v1"

      # Fix for above issue
      - key: "core.server_root"
        value: http://{{ ghost }}:{{ gport }}/

      # - key: "core.registration_policy"
      #   value: "closed"

  - name: Restart Girder Server
    girder:
      host: "{{ ghost }}"
      port: "{{ gport }}"
      scheme: "{{ gscheme }}"
      token: "{{ admin['token'] }}"
      put:
        path: "system/restart"